import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { getSingleBlogFunc } from '@/app/auth/store/Slices/BlogSlice';
import { useDispatch } from 'react-redux';
import Head from 'next/head';
import Image from 'next/image';
import user from '../../../../../public/assets/images/user.png'
import thumbimg from '../../../../../public/assets/images/aboutbanner.png'
import moment from "moment/moment";

const BlogDetaisl = () => {
   const [blogData,setBlogData]= useState(null)
    const dispatch = useDispatch()
  const router = useRouter();
const {slug} = router.query;

useEffect(()=>{
  if(slug){
    getData()
  }
},[slug])

 const getData= async()=>{
  const singleblogData = await dispatch(getSingleBlogFunc(Number(slug)))
  if(singleblogData &&  singleblogData.payload  && singleblogData.payload.success){
    setBlogData(singleblogData.payload.data)
  }
 }
  return (
    <div>
      <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
      {blogData && blogData.length > 0 && blogData.map((ele, index)=>{
      return(
        <>
        <div key={index} >
          <section className='md:bg-right  md:bg-no-repeat 2xl:bg-700 xl:bg-680 lg:bg-590 md:bg-460 relative xl:py-48 md:py-48	py-14 services-image bg-about-banner'>
            <div className='lg:max-w-xxxl md:max-w-xxxl mx-auto md:pl-7 pl-2 md:pr-7 pr-2'>
              <div className='flex flex-wrap items-center	justify-between relative'>
                <div className='lg:w-4/5 md:w-5/12'>
                  <h3 className='bg-grey3 text-lightgrey text-base inline-block rounded-lg font-semibold px-3 py-1.5'>Foodgienic</h3>
                  <h1 className='text-32 leading-52 text-dark font-bold font-montserrate py-5'>Foodgienic is the symbol of hygienic food. Our mission is to authenticate all commercial kitchens in India.</h1>
                  <div className='flex items-center'>
                    <div className='flex items-center	mr-5'>
                      <Image src={user} alt='user' className='rounded-full h-9	w-9	object-cover mr-2' />
                      <h4 className='text-grey4 text-base	font-medium	'>Tracey Wilson</h4>
                    </div>
                    <p className='text-sm text-grey4 font-montserrate'> {moment(ele?.updatedAt).format('DD-MM-YYYY')}</p>
                  </div>
                </div>
                <div className='lg:w-7/12 md:w-7/12 relative z-10 md:hidden lg:-mr-3.5	-mr-2'>

                </div>

              </div>
            </div>
          </section>
          <section className='relative xl:pt-64 xl:pb-36 xl:py-20 md:pt-40 md:pb-20 md:pt-16 pt-28 pb-20 bg-aboutbg bg-contain bg-no-repeat bg-repeat'>
            <div className='lg:max-w-xxxl md:max-w-xxxl mx-auto md:pl-7 pl-2 md:pr-7 pr-2'>
              <div className='flex flex-wrap justify-between'>
                <div className='md:w-72% w-full'>
                  <div className='mb-6'>
                    <Image
                      alt="Logo"
                      height={900}
                      width={900}
                      src={ele?.image}
                      className='md:h-466 w-full object-cover rounded-xl h-96	'
                    />
                  </div>
                  <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. Mauris id commodo libero, id pharetra felis. Pellentesque imperdiet consequat est, ut rhoncus neque pharetra eget. Nullam id sem diam. </p>
                  <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. Mauris id commodo libero, id pharetra felis. Pellentesque imperdiet consequat est. </p>
                  <h2 className='mb-2.5	font-montserate font-semibold text-2xl'>Foodgienic is the symbol of hygienic food</h2>
                  <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. Mauris id commodo libero, id pharetra felis. Pellentesque imperdiet consequat est. </p>
                  <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. Mauris id commodo libero, id pharetra felis. Pellentesque imperdiet consequat est. </p>
                  <h2 className='mb-2.5	font-montserate font-semibold text-2xl'>Foodgienic is the symbol of hygienic food</h2>
                  <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. Mauris id commodo libero, id pharetra felis. Pellentesque imperdiet consequat est. </p>
                  <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. Mauris id commodo libero, id pharetra felis. Pellentesque imperdiet consequat est. </p>
                  <div className='bg-quote-bg rounded-xl md:p-8 mb-6'>
                    <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark italic	'>“ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. ”</p>
                  </div>
                  <h2 className='mb-2.5	font-montserate font-semibold text-2xl'>Foodgienic is the symbol of hygienic food</h2>
                  <p className='font-montserrate text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6 '>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie nulla nibh, sed aliquet dui vehicula vitae. Proin ac libero metus. Mauris id commodo libero, id pharetra felis. Pellentesque imperdiet consequat est. </p>
                </div>
                <div className='md:w-24% w-full'>
                  <div className='rounded-lg overflow-hidden bg-white	shadow-2'>
                    <div className='bg-black p-3'>
                      <h3 className='text-white	font-montserrate font-medium text-xl'>Latest Posts</h3>
                    </div>
                    <div className='p-2.5'>
                      <div className='flex flex-wrap justify-between items-center border-grey-light border rounded-md p-1.5 mb-2'>
                        <div className='h-72px w-72px rounded-lg overflow-hidden	'>
                          <Image src={thumbimg} alt="latest post" className='w-full h-full object-cover rounded-lg'/>
                        </div>
                        <div className='w-[calc(100%-84px)]'>
                          <h3 class="bg-grey3 text-lightgrey text-xs inline-block rounded-lg font-semibold px-2.5 py-1">Foodgienic</h3>
                          <h4 className='text-sm font-semibold text-ellipsis overflow-hidden whitespace-nowrap xl:w-56 md:w-36 w-48 pt-1'>Foodgienic is the symbol of hygienic</h4>
                          <a href="#" className='text-orange text-xs'>Read more</a>
                        </div>
                      </div>
                      <div className='flex flex-wrap justify-between items-center border-grey-light border rounded-md p-1.5'>
                        <div className='h-72px w-72px rounded-lg overflow-hidden	'>
                          <Image src={thumbimg} alt="latest post" className='w-full h-full object-cover rounded-lg'/>
                        </div>
                        <div className='w-[calc(100%-84px)]'>
                          <h3 class="bg-grey3 text-lightgrey text-xs inline-block rounded-lg font-semibold px-2.5 py-1">Foodgienic</h3>
                          <h4 className='text-sm font-semibold text-ellipsis overflow-hidden whitespace-nowrap xl:w-56 md:w-36 w-48 pt-1'>Foodgienic is the symbol of hygienic</h4>
                          <a href="#" className='text-orange text-xs'>Read more</a>
                        </div>
                      </div>
                    </div>
                      
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* <section className='md:bg-right md:bg-no-repeat 2xl:bg-700 xl:bg-680 lg:bg-590 md:bg-460 relative xl:py-32 lg:py-20 md:py-14 py-14' >
            <div className='lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2	'>
              <div className='flex flex-wrap items-center	justify-between relative'>
                <div className='w-full lg:w-5/12	'>
                    <h1 className='font-montserrate xl:text-6xl font-bold text-dark lg:mb-6 md:mb-2 mb-2.5	md:text-4xl lg:text-5xl text-3xl relative lg:before:content-[attr(before)] before:absolute before:bg-aboutus before:bg-10%	before:bg-no-repeat	before:-z-10 xl:before:-top-6 lg:before:-top-6 md:before:-top-2 before:-top-1 lg:before:-left-2.5 md:before:left-0 xl:before:w-34r md:before:h-28 before:h-20 md:before:w-80 before:w-60'> {ele?.title}</h1>
                    <p className='font-montserrate lg:text-xl text-sm md:text-lg font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6'>{ele?.title} </p>
                </div>
                <div className='lg:w-7/12 md:full relative z-10 '>
                  <Image
                    alt="Logo"
                    height={850}
                    width={850}
                    src={ele?.image}
                  />
                </div>
              </div>
            </div>

          </section>
          <section className='relative xl:pb-36 md:pb-20 xl:pt-36 md:pt-20 pt-28 pb-20'>
            <div className='lg:max-w-xxxl md:max-w-xxxl mx-auto  pl-7	pr-7 '>
                <div className='flex flex-wrap items-center	justify-between relative'>
                  <div className='w-full relative z-10'>
                      <div >
                    <p className="font-montserrate font-medium text-dark text-base leading-6 text-sm line-clamp-3 mb-2.5 mt-3" dangerouslySetInnerHTML={{ __html: ele?.description }}></p>
                      </div>
                
                
                  </div>
                </div>
              
            </div>
          </section>     */}

          </div>
        </>
      )
    })}
          
      </main>
    </>
    </div>
  )
}

export default BlogDetaisl
