
import { useState} from "react";
import Head from 'next/head'
import AdminNAv from '@/components/forms/AdminNav';
import { useRouter } from 'next/navigation'
export default function AdminPage() {
  const router = useRouter()
  console.log("router",router)
  const [isOpen, setOpen] = useState(false);
  const userToggleForm = () => setOpen(!isOpen);
  const hideSidebar = isOpen ? 'xl:w-3/2 lg:w-3/4 md:w-3/5 w-full' : ' xl:w-full lg:w-full w-full';

const cardData=[
  {
    "id":"1",
    "title":"Service",
    "path": "service",
    "dis": "Lorem ipsum dolor",
  },
  {
    "id":"2",
    "title":"About",
    "path": "about",
    "dis": "Lorem ipsum dolor",
  },
  {
    "id":"3",
    "title":"Home",
    "path": "home",
    "dis": "Lorem ipsum dolor",
  },
  {
    "id":"4",
    "title":"Price",
    "path": "price",
    "dis": "Lorem ipsum dolor",
  },
  {
    "id":"5",
    "title":"Blog",
    "path": "blog",
    "dis": "Lorem ipsum dolor",
  },
  {
    "id":"6",
    "title":"Partners/Agencies",
    "path": "partners",
    "dis": "Lorem ipsum dolor",
  },
  
]


const editPagesData=(item)=>{
  if(item){
    router.push(`/admin/pages/Collections/${item}`)
  }

}
  return (
    <>
    <Head>
        <title>Pages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
            <div className='content-area mt-4  md:pl-8 w-full'>
              <div className='title-section mb-5 px-8 py-4 bg-white rounded-xl shadow-light'>
                <h3 className='text-2xl font-bold'>Pages</h3>
              </div>
                {cardData && cardData.map((ele,index)=>{
                  return(
                  <div key={index} className='card1 md:px-8 md:py-4 px-4 py-4 bg-white rounded-xl shadow-light w-full mb-5 flex flex-wrap justify-between items-center hover:bg-blackLight ease-in duration-300 hover:ease-in group hover:text-white hover:border-white'>
                      <div className='text-left xl:mb-0 lg:mb-4 flex items-center'>
                        <span className='border sm:w-14 sm:h-14 h-11 w-11 sm:text-2xl text-xl font-bold border-orange text-orange inline-block rounded-full group-hover:border-inherit flex justify-center items-center group-hover:text-white'>{ele.id}</span>
                        <div className="sm:ml-4 ml-2.5">
                          <h5 className='sm:text-2xl text-lg font-bold tracking-normal mb-0'>{ele.title}</h5>
                          {/* <h3 className='text-sm sm:text-18 sm:text-16 font-medium tracking-normal'>{ele.dis}</h3> */}
                        </div>
                      </div>
                      <div className='right flex justify-end'>
                        <button className="flex justify-center items-center text-sm font-semibold border border-black rounded-full ease-in duration-500 bg-blackLight text-white	sm:p-2 hover:bg-yellow hover:text-white hover:border-yellow sm:w-24 group-hover:border-inherit py-1	px-3.5	"onClick={()=>editPagesData(ele.path)}> 
                          <svg className="mr-2 w-3	sm:w-4	" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g clip-path="url(#clip0_308_693)">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M9.63526 3.28563L12.7172 6.37214L3.96469 15.144C3.84913 15.2598 3.6924 15.3249 3.52898 15.325L0.842487 15.5C0.672332 15.5001 0.499993 15.3275 0.5 15.157L0.702237 12.4941C0.702244 12.3304 0.76717 12.1733 0.882732 12.0575L9.63526 3.28563Z" fill="white"/>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M10.6644 2.25695L12.2053 0.713154C12.489 0.428949 12.9489 0.428949 13.2326 0.713154L15.2872 2.77155C15.5709 3.05575 15.5709 3.51654 15.2872 3.80075L13.7463 5.34454L10.6644 2.25695Z" fill="white"/>
                            </g>
                            <defs>
                            <clipPath id="clip0_308_693">
                            <rect width="16" height="16" fill="white"/>
                            </clipPath>
                            </defs>
                          </svg>Edit
                        </button>
                      </div>
                  </div>
                  )
                })}
            </div>

    </>
  )
}


AdminPage.getLayout = function getLayout(page) {
  return (
    <>
     {page}
    </>
  )
}