import Head from 'next/head'
import Image from 'next/image'
import { motion } from "framer-motion"
import { Inter } from '@next/font/google'
import { useEffect, useState } from "react";
import Link from 'next/link'
import service3 from '../../public/assets/images/service3.png'
import contact from '../../public/assets/images/contact.png'
import arrow from '../../public/assets/images/arrow.png'
import fb from '../../public/assets/images/fb.svg'
import linkedin from '../../public/assets/images/linkedin.svg'
import twitter from '../../public/assets/images/twitter.svg'
import instagram from '../../public/assets/images/instagram.svg'
import phone from '../../public/assets/images/phone.svg'
import terms from '../../public/assets/images/terms.svg'
import privacy from '../../public/assets/images/privacy.svg'
import mail from '../../public/assets/images/mail.svg'
import location from '../../public/assets/images/location.svg'
import leave1 from '../../public/assets/images/leave1.svg'
import leave2 from '../../public/assets/images/leave2.svg'
import user from '../../public/assets/images/user.svg'
import restaurant from '../../public/assets/images/restaurant.svg'
import dots3 from '../../public/assets/images/dots3.png'
import dots from '../../public/assets/images/dots.png'
import dots2 from '../../public/assets/images/dots2.png'

import logo1 from '../../public/assets/images/log1.png'
import logo2 from '../../public/assets/images/img2.png'
import logo3 from '../../public/assets/images/img3.png'
import logo4 from '../../public/assets/images/img4.png'
import logo5 from '../../public/assets/images/img5.png'

import flogo1 from '../../public/assets/images/flogo1.png'
import flogo2 from '../../public/assets/images/flogo2.png'
import flogo3 from '../../public/assets/images/flogo3.png'
import flogo4 from '../../public/assets/images/flogo4.png'
import flogo5 from '../../public/assets/images/flogo5.png'

import UserSignup from '@/components/forms/userSignup';
import RestaurantSignup from '@/components/forms/restaurantSignup';
import { Button, Paper } from '@mui/material';
import Slider from 'react-slick';
import { constants, carouselSettings } from '@/common/Constant';
// import { HomeData } from '@/common/PagesContent';
import { useDispatch, useSelector } from 'react-redux';
import { getAllDynamicData, getHomeData } from '@/app/auth/store/Slices/DynamicContentSlice';
// console.log("HomeData",HomeData)
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  
  const [isOpen, setOpen] = useState(false);
  const [resdata, setResdata] = useState(null);
  const [partners, setPartners] = useState(null);
  const userToggleForm = () => setOpen(!isOpen);
  const RestaurantToggleForm = () => setOpen(false);
  const conditionRestaurant = isOpen ? 'before:hidden' : '';
  const conditionUser = isOpen ? '' : 'before:hidden';
  const dispatch = useDispatch()
  const selecter = useSelector(getHomeData)
  let HomeData = []
  HomeData.push(selecter && selecter)
  console.log("HomeData>>>>>>>>>",HomeData)
  useEffect(()=>{
    // console.log("USE EFFECT RUNN")
    getApi()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[])

  const getApi = async () => {
    const data = await dispatch(getAllDynamicData())
    setPartners(data?.payload?.data?.partners_page_sections);
  }

  useEffect(() => {
    getVerifideRestaurantData()

  }, [])
 const getVerifideRestaurantData = () => {
  fetch(`${constants.URLLOCAL}/restaurent/getVerifiedRestaurent`)
    .then(response => {
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      return response.json();
    })
    .then(json => {
      console.log("fdsfsdf",json);
      setResdata(json);
    })
    .catch(error => {
      console.error('Error fetching restaurant data:', error);
    });
};
const [activeTab, setActiveTab] = useState('profile');

  const handleTabClick = (tab) => {
    setActiveTab(tab);
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        <script
          src="https://checkout.razorpay.com/v1/checkout.js"
          async
        ></script>
      </Head>
      <main>
        {HomeData &&
          HomeData.length > 0 &&
          HomeData.map((ele, index) => {
            return (
              <div key={index}>
                <section className="bg-bg xl:bg-right-bottom bg-100% md:pt-4 relative pt-12 pb-12	">
                  <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2 ">
                    <div className="flex flex-wrap items-center	justify-between relative">
                      <div className="lg:w-5/12	md:w-5/12">
                        <h1 className="font-montserrate lg:text-5xl font-bold text-dark lg:mb-6 md:mb-2 mb-2.5 md:text-4xl  text-3xl  relative lg:before:content-[attr(before)] before:absolute before:bg-eat md:before:h-28 before:h-16 before:h-1 xl:before:w-61r md:before:w-40r sm:before:w-30r before:w-80 before:bg-10%	before:bg-no-repeat	before:-z-10 xl:before:-top-6 md:before:-top-2 before:-top-2.5 lg:before:-left-0 md:before:left-0">
                          {ele?.home_First_Section?.first_title}
                        </h1>
                        <p className="font-montserrate  text-sm md:text-lg font-medium text-dark md:leading-8 leading-6 mb-6 text-sm">
                          {ele?.home_First_Section?.first_descriptions}
                        </p>
                      </div>
                      <div className="lg:w-7/12 md:w-7/12 relative z-10">
                        <Image
                          alt="Banner Image"
                          src={ele?.home_First_Section?.first_Img}
                          width={879}
                          height={781}
                        />
                      </div>
                    </div>
                  </div>
                  <div className="absolute right-0 -bottom-52 hidden md:block">
                    <Image
                      alt="Dots"
                      src={dots}
                      className="md:w-3/5 xl:w-full md:ml-auto md:w-10/12 xl:m-0"
                    />
                  </div>
                </section>
                <section className="relative xl:py-24	lg:py-20 md:pt-16 pt-10">
                  <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto md:pl-7 pl-2 md:pr-7 pr-2 ">
                    <div className="flex flex-wrap items-center	justify-between">
                      <div className="lg:w-5/12	md:w-5/12">
                        <h2 className="font-montserrate lg:text-5xl font-bold text-dark lg:mb-6 md:mb-6 relative lg:before:content-[attr(before)] before:absolute before:bg-about xl:before:h-24 md:before:h-20 before:h-20 xl:before:w-96 md:before:w-52 before:w-52 before:w-24 before:bg-10% before:bg-no-repeat before:-z-10 xl:before:-top-6 md:before:-top-2 before:-top-1 md:text-4xl md:md:mb-2 text-4xl mb-2.5 ">
                          {ele?.home_Second_Section?.Second_title}
                        </h2>
                        <p className="font-montserrate  text-sm md:text-lg font-medium text-dark md:leading-8 leading-6 text-dark mb-6 ">
                          {ele?.home_Second_Section?.Second_descriptions}
                        </p>
                      </div>
                      <div className="lg:w-6/12 md:w-6/12">
                        <div className=" bg-gradient-to-r from-black to-white p-1 rounded-b-full rounded-tl-full rounded-tr-180 md:mt-0	mt-8	">
                          <div className="overflow-hidden rounded-b-full rounded-tl-full rounded-tr-180 relative md:h-466">
                            <Image
                              alt="Banner Image"
                              src={ele?.home_Second_Section?.Second_Img}
                              className="object-cover h-full w-full sm:ease-in sm:duration-700 sm:hover:h-550 sm:hover:w-550"
                              width={894}
                              height={597}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="absolute left-0 xl:-bottom-2/4 -left-1.5 hidden md:block">
                    <Image
                      alt="Dots"
                      src={dots2}
                      className="md:w-3/5 xl:w-full md:mr-auto md:w-10/12 xl:m-0"
                    />
                  </div>
                </section>
                <section className="bg-service lg:py-56	bg-center	bg-100% bg-no-repeat md:py-32 pb-24	pt-28">
                  <div className=" lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
                    <h2 className="font-montserrate lg:text-5xl md:text-4xl font-bold text-dark lg:mb-20 md:mb-10 text-center z-10 relative lg:before:content-[attr(before)] before:absolute before:bg-servicetext xl:before:h-28 before:h-20 xl:before:w-42r sm:before:w-96 before:w-80 before:bg-10% before:bg-no-repeat md:before:-top-5 before:-top-4 xl:before:-left-2.5 md:before:-left-2.5 before:right-0 before:left-0 before:mx-auto before:-z-10 text-4xl mb-8">
                      {ele?.home_Third_Section?.Third_title}
                    </h2>

                    <Slider
                      className="lg:max-w-xxxl md:max-w-xxxl max-w-md mx-auto pl-7 pr-7"
                      {...carouselSettings}
                    >
                      {ele &&
                        ele?.home_Third_Section &&
                        ele?.home_Third_Section?.Third_descriptions_section?.map(
                          (item, index) => {
                            return (
                              <div key={index}>
                                <div className="flex flex-wrap items-center	justify-between md:relative">
                                  <div className="lg:w-11/12 w-full lg:px-2.5 md:px-2.5 md:mb-0 mb-7	">
                                    <div className="sm:w-3/5 sm:mx-auto md:w-full w-full overflow-hidden rounded-l-full	rounded-tr-full	xl:rounded-br-180 lg:rounded-br-180 md:rounded-br-100 rounded-br-100 rounded-br-1-0  xl:h-96 lg:h-72 md:h-60 sm:h-72 h-64">
                                      <Image
                                        alt="Assured Hygiene"
                                        src={item.image}
                                        className="object-cover h-full w-full sm:ease-in sm:duration-700 sm:hover:h-500 sm:hover:w-500"
                                        width={917}
                                        height={616}
                                      />
                                    </div>
                                    <h3 className="font-montserrate xl:text-2xl lg:text-lg font-semibold text-center xl:mt-11 lg:mt-8 xl:max-w-xs xl:mx-auto md:mt-3.5 mt-3	">
                                      {item.descriptions}
                                    </h3>
                                  </div>
                                </div>
                              </div>
                            );
                          }
                        )}
                    </Slider>
                  </div>
                </section>
              </div>
            );
          })}

        <section className="button-name-slider pt-24 md:pt-0">
          {resdata && resdata.data && resdata.data.length > 0 ? (
            <>
              <h2 className='font-montserrate lg:text-5xl md:text-4xl font-bold text-dark lg:mb-20 md:mb-10 text-center z-10 relative before:content="Verified Restaurants" xl:before:h-52 xl:before:w-3/6 lg:before:h-52 before:h-12 lg:before:w-96 md:before:w-72 before:w-72 before:h-12 md:before:w-96 before:bg-10% before:bg-no-repeat xl:before:-top-10 before:-top-1 lg:before:-top-6 md:before:-top-2.5 before:-left-2.5 before:right-0 before:left-0 before:mx-auto before:-z-10 text-4xl mb-8'>
                Verified Restaurants
              </h2>
              <Slider
                className="md:pl-7 pl-2 md:pr-7 pr-2 home-varified-slider"
                {...carouselSettings}
              >
                {resdata &&
                  resdata.data &&
                  resdata.data.length > 0 &&
                  resdata.data.map((val, index) => {
                    return (
                      <div key={index}>
                        <div className="px-5 my-10">
                          <div>
                            <div className="w-full bg-white drop-shadow-xl rounded-xl truncate  home-restaurant">
                              <div className="image w-full">
                                <div className="bg-orange-400 py-2 px-3 text-10 text-white text-center w-48 absolute top-4 -left-14 -rotate-45">
                                  Verified
                                </div>
                                <Image
                                  className="w-full truncate object-cover h-64	"
                                  alt="Standard Operating Procedures"
                                  src={val.image}
                                  width={400}
                                  height={400}
                                />
                              </div>
                              <div className="content p-5 restaurant-text">
                                <div className="mb-2 restaurant-kitchen">
                                  <h2 className="text-base font-semibold font-montserrate">
                                    {" "}
                                    <Image
                                      style={{ display: "inline-block" }}
                                      className="mr-3"
                                      src="/assets/images/kitchen.svg"
                                      alt="kitchen"
                                      width={18}
                                      height={18}
                                    />{" "}
                                    {val.restaurantname}
                                  </h2>
                                </div>
                                <div className="mb-2 restaurant-address">
                                  <div className="text-base font-semibold font-montserrate">
                                    {" "}
                                    <Image
                                      style={{ display: "inline-block" }}
                                      className="mr-3"
                                      src="/assets/images/location.svg"
                                      alt="location"
                                      width={18}
                                      height={18}
                                    />{" "}
                                    {val.streetAddress}, {val.city}, {val.state}
                                    
                                  </div>
                                </div>
                                <div className="mb-2 restaurant-phn">
                                  <p className="text-base font-semibold font-montserrate">
                                    {" "}
                                    <Image
                                      style={{ display: "inline-block" }}
                                      className="mr-3"
                                      src="/assets/images/tel.svg"
                                      alt="phone"
                                      width={18}
                                      height={18}
                                    />{" "}
                                    {val.phone}
                                  </p>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    );
                  })}
              </Slider>
            </>
          ) : null}
        </section>

        {/* Partner Section */}
        <section className="bg-center	bg-100% bg-no-repeat md:py-32 pb-24	pt-28">
          <div className=" lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
            <h2 className="font-montserrate lg:text-5xl md:text-4xl font-bold text-dark lg:mb-20 md:mb-10 text-center z-10 relative lg:before:content-[attr(before)] before:absolute xl:before:h-28 before:h-20 xl:before:w-42r sm:before:w-96 before:w-80 before:bg-10% before:bg-no-repeat md:before:-top-5 before:-top-4 xl:before:-left-2.5 md:before:-left-2.5 before:right-0 before:left-0 before:mx-auto before:-z-10 text-4xl mb-8">
              Partners
            </h2>
            <Slider className="lg:max-w-xxxl md:max-w-xxxl max-w-md mx-auto pl-7 pr-7"
                      {...carouselSettings}
                    >
            <div className=''>
            {partners?.partner &&
              partners?.partner?.map((item, index) => {

                return (
                
                    <div key={index} className="lg:w-11/12 w-full lg:px-2.5 md:px-2.5 md:mb-0 mb-7">
                     
                       
                          <div className="sm:w-3/5 sm:mx-auto md:w-full w-full xl:h-96 lg:h-72 md:h-60 sm:h-72 h-56 w-full bg-white drop-shadow-xl rounded-xl truncate">
                            <Image
                              alt="Assured Hygiene"
                              src={item.image}
                              className="w-full truncate object-cover h-full"
                              width={300}
                              height={300}
                            />
                          </div>
                     </div>
                     
                
            
                );
              })}
              </div>
            </Slider>
          </div>
        </section>

        {/* Agency Section */}
        <section className="bg-center	bg-100% bg-no-repeat md:py-32 pb-24	pt-28">
          <div className=" lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
            <h2 className="font-montserrate lg:text-5xl md:text-4xl font-bold text-dark lg:mb-20 md:mb-10 text-center z-10 relative lg:before:content-[attr(before)] before:absolute xl:before:h-28 before:h-20 xl:before:w-42r sm:before:w-96 before:w-80 before:bg-10% before:bg-no-repeat md:before:-top-5 before:-top-4 xl:before:-left-2.5 md:before:-left-2.5 before:right-0 before:left-0 before:mx-auto before:-z-10 text-4xl mb-8">
              Agencies
            </h2>
            
            <Slider className="lg:max-w-xxxl md:max-w-xxxl max-w-md mx-auto pl-7 pr-7"
                      {...carouselSettings}
                    >
                      <div className=''>
                {partners?.agency &&
                partners?.agency?.map((item, index) => {
                  return (
                    <div key={index} className="lg:w-11/12 w-full lg:px-2.5 md:px-2.5 md:mb-0 mb-7">
                      <div className="flex flex-wrap items-center	justify-between md:relative">
                       
                          <div className="sm:w-3/5 sm:mx-auto md:w-full w-full xl:h-96 lg:h-72 md:h-60 sm:h-72 h-56 w-full bg-white drop-shadow-xl rounded-xl truncate">
                            <Image
                              alt="Assured Hygiene"
                              src={item.image}
                              className="w-full truncate object-cover h-full"
                              width={300}
                              height={300}
                            />
                          </div>
                        
                      </div>
                    </div>
                  );
                })}
                </div>
                </Slider>
            
          </div>
        </section>

        {/* Brand Section */}
        <section className="bg-center	bg-100% bg-no-repeat md:py-32 pb-24	pt-28">
          <div className=" lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
            <h2 className="font-montserrate lg:text-5xl md:text-4xl font-bold text-dark lg:mb-20 md:mb-10 text-center z-10 relative lg:before:content-[attr(before)] before:absolute xl:before:h-28 before:h-20 xl:before:w-42r sm:before:w-96 before:w-80 before:bg-10% before:bg-no-repeat md:before:-top-5 before:-top-4 xl:before:-left-2.5 md:before:-left-2.5 before:right-0 before:left-0 before:mx-auto before:-z-10 text-4xl mb-8">
              Brands
            </h2>
            {partners?.brand &&
              partners?.brand?.map((item, index) => {
                return (
                  <div key={index}>
                    <div className="flex flex-wrap items-center	justify-between md:relative">
                      <div className="lg:w-11/12 w-full lg:px-2.5 md:px-2.5 md:mb-0 mb-7	">
                        <div className="sm:w-3/5 sm:mx-auto md:w-full w-full overflow-hidden rounded-l-full	rounded-tr-full	xl:rounded-br-180 lg:rounded-br-180 md:rounded-br-100 rounded-br-100 rounded-br-1-0  xl:h-96 lg:h-72 md:h-60 sm:h-72 h-64">
                          <Image
                            alt="Assured Hygiene"
                            src={item.image}
                            className="object-cover h-full w-full sm:ease-in sm:duration-700 sm:hover:h-500 sm:hover:w-500"
                            width={300}
                            height={300}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
          </div>
        </section>

        {/* </section> */}

        <section className="lg:pt-24 xl:pb-20	lg:pb-0 relative md:pt-16	pt-12	">
          <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2 relative">
            <div className="flex justify-center	flex-wrap">
              <div className="mx-2.5 w-full mb-3.5 sm:mb-0 sm:w-auto">
                <h4
                  onClick={userToggleForm}
                  className={`lg:w-72 md:w-56 text-center lg:py-6	md:py-3.5	font-montserrate lg:text-lg md:text-sm	text-dark hover:text-orange-300 font-semibold bg-white border border-black rounded-md	cursor-pointer relative before:content-[attr(before)] before:absolute before:border-t-15 before:border-x-10 before:border-t-black hover:border-orange-300 before:border-x-transparent	before:left-10	before:-bottom-4 	py-2.5 px-3.5 text-sm ${conditionUser}`}
                >
                  Signup as User{" "}
                  <Image
                    alt="Sign Up"
                    src={user}
                    className="lg:w-6	inline-block ml-1 md:w-4	w-4"
                  />
                </h4>
              </div>
              <div className="mx-2.5 w-full mb-3.5 sm:mb-0 sm:w-auto">
                <h4
                  onClick={RestaurantToggleForm}
                  className={`lg:w-72 md:w-56 text-center lg:py-6	md:py-3.5	font-montserrate lg:text-lg md:text-sm	text-dark hover:text-orange-300 font-semibold bg-white border border-black rounded-md	cursor-pointer relative before:content-[attr(before)] before:absolute before:border-t-15 before:border-x-10 before:border-t-black	hover:border-orange-300 before:border-x-transparent	before:left-10 before:-bottom-4 py-2.5 px-3.5 text-sm ${conditionRestaurant}`}
                >
                  Signup as Restaurant{" "}
                  <Image
                    alt="Restaurant"
                    src={restaurant}
                    className="lg:w-6	inline-block	ml-1 md:w-4 w-4"
                  />
                </h4>
              </div>
            </div>
            <div className="py-7 xl:max-w-5xl xl:mx-auto bg-grey lg:p-8 rounded-lg	drop-shadow-sm border-t-2	border-black mt-4 md:py-9	relative z-10">
              {isOpen ? <UserSignup /> : <RestaurantSignup />}
            </div>
            <div className="absolute lg:-top-20 left-1/4 md:top-10 -z-10 hidden md:block">
              <Image alt="Dots" src={dots3} />
            </div>
          </div>
          <div className="lg:flex md:hidden	absolute left-0 right-0 items-center	justify-between	mx-auto	xl:max-w-xxl xl:-bottom-48 lg:-bottom-60 lg:max-w-none -z-10 hidden">
            <div className="">
              <Image alt="leave1" src={leave1} />
            </div>
            <div className="">
              <Image alt="leave2" src={leave2} />
            </div>
          </div>

          <div className="absolute right-0 -bottom-1/3 hidden md:block">
            <Image
              alt="Dots"
              src={dots}
              className="md:w-3/5 xl:w-full md:ml-auto md:w-10/12 xl:m-0"
            />
          </div>
        </section>

        <section className="bg-contact lg:pt-60 lg:pb-40	md:pt-64 md:pb-32	pt-60	pb-14">
          <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
            <div className="flex flex-wrap justify-between items-center">
              <div className="lg:w-5/12 md:w-5/12 relative md:order-none order-2">
                <h2 className="font-montserrate text-lg lg:text-5xl font-bold text-dark lg:mb-6 md:mb-6 p-1">
                  Contact
                </h2>

                <ul>
                  <li className="font-montserrate text-sm md:text-base	font-semibold	text-black100 mb-1.5 hover:text-yellow p-1">
                    <Image
                      alt="phone"
                      src={phone}
                      className="inline-block mr-3.5"
                    />
                    <Link
                      href="tel:91 81468-02482"
                      className="ease-in duration-300"
                    >
                      +91 7814606432
                    </Link>
                  </li>
                  <li className="font-montserrate text-sm md:text-base	font-semibold	text-black100 mb-1.5 hover:text-yellow p-1">
                    <Image
                      alt="mail"
                      src={mail}
                      className="inline-block mr-3.5"
                    />
                    <Link
                      href="mailto:support@foodgienic.com"
                      className="ease-in duration-300"
                    >
                      support@foodgienic.com
                    </Link>
                  </li>

                  <li className="font-montserrate text-sm md:text-base	font-semibold	text-black100 mb-1.5 hover:text-yellow p-1">
                    <Image
                      alt="terms"
                      src={terms}
                      className="inline-block mr-3.5"
                    />
                    <Link href="/terms" className="ease-in duration-300">
                      Terms & Conditions
                    </Link>
                  </li>

                  <li className="font-montserrate text-sm md:text-base	font-semibold	text-black100 mb-1.5 hover:text-yellow p-1">
                    <Image
                      alt="privacy"
                      src={privacy}
                      className="inline-block mr-3.5"
                    />
                    <Link href="/policy" className="ease-in duration-300">
                      Privacy Policy
                    </Link>
                  </li>

                  <li className="font-montserrate text-sm md:text-base flex items-start font-semibold	text-black100 mb-1.5 xl:max-w-md hover:text-yellow p-1">
                    <Image
                      alt="location"
                      src={location}
                      className="inline-block mr-3.5 mt-1.5"
                    />
                    <Link
                      href="https://goo.gl/maps/WUpd8uPosEpQJuY76"
                      className="ease-in duration-300 w-11/12	"
                      target="_blank"
                    >
                      #161, Second Floor, Sector 124, Sunny Enclave Extension,
                      kharar, SAS Nagar, Punjab-140301
                    </Link>
                  </li>
                </ul>

                <ul className="flex mt-8">
                  <li className="mr-2.5	bg-white w-12 h-12 rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full"
                    >
                      <Image alt="facebook" src={fb} />
                    </Link>
                  </li>
                  <li className="mr-2.5	bg-white w-12 h-12	rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full"
                    >
                      <Image alt="Linkedin" src={linkedin} />
                    </Link>
                  </li>
                  <li className="mr-2.5	bg-white w-12 h-12	rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full"
                    >
                      <Image alt="twitter" src={twitter} />
                    </Link>
                  </li>
                  <li className="mr-2.5	bg-white w-12 h-12	rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full"
                    >
                      <Image alt="instagram" src={instagram} />
                    </Link>
                  </li>
                </ul>
                <div className="absolute md:right-0	xl:bottom-0	lg:bottom-5	md:hidden lg:block hidden">
                  <Image
                    alt="arrow"
                    src={arrow}
                    className="xl:w-full lg:w-3/5 xl:ml-0	lg:ml-auto"
                  />
                </div>
              </div>

              <div className="w-full lg:w-7/12	md:w-7/12 mt-8	md:0 md:order-none order-1">
                <Image alt="contact" src={contact} className=" w-full" />
              </div>
            </div>
          </div>
        </section>

        <section className="py-16 hidden">
          <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
            <div className="mb-4">
              <ul
                className="flex flex-wrap -mb-px text-sm font-medium text-center"
                role="tablist"
              >
                <li
                  className={`${
                    activeTab === "profile"
                      ? "border-b-2 border-orange text-orange"
                      : ""
                  } md:w-30% w-full text-2xl  border-b-2`}
                  role="presentation"
                >
                  <button
                    className="inline-block p-4 rounded-t-lg focus:outline-none"
                    id="profile-tab"
                    type="button"
                    role="tab"
                    aria-controls="profile"
                    aria-selected={activeTab === "profile"}
                    onClick={() => handleTabClick("profile")}
                  >
                    Our Customers
                  </button>
                </li>
                <li
                  className={`${
                    activeTab === "dashboard"
                      ? "border-b-2 border-orange text-orange"
                      : ""
                  } md:w-30% w-full text-2xl  border-b-2`}
                  role="presentation"
                >
                  <button
                    className="inline-block p-4 rounded-t-lg focus:outline-none"
                    id="dashboard-tab"
                    type="button"
                    role="tab"
                    aria-controls="dashboard"
                    aria-selected={activeTab === "dashboard"}
                    onClick={() => handleTabClick("dashboard")}
                  >
                    Brand Partners
                  </button>
                </li>
                <li
                  className={`${
                    activeTab === "settings"
                      ? "border-b-2 border-orange text-orange"
                      : ""
                  } md:w-30% w-full text-2xl  border-b-2`}
                  role="presentation"
                >
                  <button
                    className="inline-block p-4 rounded-t-lg focus:outline-none"
                    id="settings-tab"
                    type="button"
                    role="tab"
                    aria-controls="settings"
                    aria-selected={activeTab === "settings"}
                    onClick={() => handleTabClick("settings")}
                  >
                    Financial Partners
                  </button>
                </li>
              </ul>
              <div id="myTabContent" className="mt-1">
                <div
                  className={`p-4 ${activeTab === "profile" ? "" : "hidden"}`}
                  id="profile"
                  role="tabpanel"
                  aria-labelledby="profile-tab"
                >
                  <div className="flex	justify-between	flex-wrap	items-center	">
                    <div>
                      <Image src={logo1} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo2} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo3} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo4} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo5} alt="logo" />
                    </div>
                  </div>
                </div>
                <div
                  className={`p-4 ${activeTab === "dashboard" ? "" : "hidden"}`}
                  id="dashboard"
                  role="tabpanel"
                  aria-labelledby="dashboard-tab"
                >
                  <div className="flex	justify-between	flex-wrap	items-center	">
                    <div>
                      <Image src={logo1} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo2} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo3} alt="logo" />
                    </div>

                    <div>
                      <Image src={logo5} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo4} alt="logo" />
                    </div>
                  </div>
                </div>
                <div
                  className={`p-4 ${activeTab === "settings" ? "" : "hidden"}`}
                  id="settings"
                  role="tabpanel"
                  aria-labelledby="settings-tab"
                >
                  <div className="flex	justify-between	flex-wrap	items-center	">
                    <div>
                      <Image src={logo1} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo2} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo4} alt="logo" />
                    </div>
                    <div>
                      <Image src={logo3} alt="logo" />
                    </div>

                    <div>
                      <Image src={logo5} alt="logo" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-grey py-16 hidden">
          <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
            <h2 className="font-montserrate text-2xl	 lg:text-6xl font-bold text-dark lg:mb-9 mb-9 p-1 text-center">
              Let’s get started
            </h2>
            <div className="flex justify-center flex-wrap">
              <button className="border	border-orange md:px-9 py-3 px-6 text-lg	text-orange md:mr-3 ease-in duration-500 hover:bg-yellow hover:text-white w-full md:mb-0 mb-3 md:w-auto	">
                New to Food Genic Labs?
              </button>
              <button className="border	border-black md:px-9 py-3 px-4 text-lg text-black md:ml-3 ease-in duration-500 hover:bg-black hover:text-white w-full md:w-auto	">
                Already to Food Genic Labs?
              </button>
            </div>
          </div>
        </section>

        <section className="py-20 hidden">
          <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
            <div className="flex justify-between	flex-wrap	">
              <div className="md:w-1/4 w-full	md:mb-0 mb-4">
                <h2 className="text-2xl	font-bold pb-3 relative">
                  Business Types
                </h2>
                <span className="block w-9	border-b-2 border-orange mb-5 after:block after:border-b-2 after:border-orange"></span>

                <ul>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Electronics & Mobiles
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Lifestyle
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Automobile
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Grocery
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Healthcare
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Hospitality
                    </a>
                  </li>
                </ul>
              </div>
              <div className="md:w-1/4 w-full	md:mb-0 mb-4">
                <h2 className="text-2xl	font-bold pb-3 relative">
                  Payments Instore
                </h2>
                <span className="block w-9	border-b-2 border-orange mb-5 after:block after:border-b-2 after:border-orange"></span>

                <ul>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Plutus Smart
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Plutus PoS
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Plutus QR
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Palm
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      AllTap
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Hub
                    </a>
                  </li>
                </ul>
              </div>
              <div className="md:w-1/4 w-full md:mb-0 mb-4">
                <h2 className="text-2xl	font-bold pb-3 relative">
                  Business Types
                </h2>
                <span className="block w-9	border-b-2 border-orange mb-5 after:block after:border-b-2 after:border-orange"></span>

                <ul>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Electronics & Mobiles
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Lifestyle
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Automobile
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Grocery
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Healthcare
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Hospitality
                    </a>
                  </li>
                </ul>
              </div>
              <div className="md:w-1/4 w-full	">
                <h2 className="text-2xl	font-bold pb-3 relative">
                  Business Types
                </h2>
                <span className="block w-9	border-b-2 border-orange mb-5 after:block after:border-b-2 after:border-orange"></span>

                <ul>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Electronics & Mobiles
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Lifestyle
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Automobile
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Grocery
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Healthcare
                    </a>
                  </li>
                  <li className="text-base mb-1">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Hospitality
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            <div className="border-t mt-6 pt-6 flex justify-between items-center flex-wrap">
              <div className="md:w-1/2	">
                <ul className="flex items-center flex-wrap md:text-xs text-0">
                  <li className="text-sm pr-2.5  md:w-auto w-full md:mb-0 mb-3">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Privacy Policy
                    </a>
                  </li>
                  |
                  <li className="text-sm md:pr-2.5 md:pl-2.5  md:w-auto w-full md:mb-0 mb-3">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Terms of Use
                    </a>
                  </li>
                  |
                  <li className="text-sm md:pr-2.5 md:pl-2.5  md:w-auto w-full md:mb-0 mb-3">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Refund Policy
                    </a>
                  </li>
                  |
                  <li className="text-sm md:pl-2.5  md:w-auto w-full md:mb-0 mb-3">
                    <a
                      href="#"
                      className="ease-in duration-500 hover:text-orange"
                    >
                      Vulnerability Disclosure Policy
                    </a>
                  </li>
                </ul>
              </div>
              <div className="md:w-1/2	md:mt-0 mt-4">
                <ul className="flex justify-end	">
                  <li className="mr-2.5	bg-white w-12 h-12 rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500 border">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full"
                    >
                      <Image alt="facebook" src={fb} />
                    </Link>
                  </li>
                  <li className="mr-2.5	bg-white w-12 h-12	rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500 border">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full"
                    >
                      <Image alt="Linkedin" src={linkedin} />
                    </Link>
                  </li>
                  <li className="mr-2.5	bg-white w-12 h-12	rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500 border">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full"
                    >
                      <Image alt="twitter" src={twitter} />
                    </Link>
                  </li>
                  <li className="mr-2.5	bg-white w-12 h-12	rounded-lg	drop-shadow-sm hover:bg-yellow ease-in duration-500 border">
                    <Link
                      href="/"
                      target="_blank"
                      className="flex	items-center justify-center h-full w-full "
                    >
                      <Image alt="instagram" src={instagram} />
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <div className="flex items-center justify-start	mt-2 flex-wrap">
              <Image
                src={flogo1}
                alt="logo"
                className="md:w-36 w-46% md:mr-3 md:mt-0 mt-5"
              />
              <Image
                src={flogo2}
                alt="logo"
                className="md:w-36 w-46% md:mr-3 md:mt-0 mt-5"
              />
              <Image
                src={flogo3}
                alt="logo"
                className="md:w-36	w-46% md:mr-3 md:mt-0 mt-5"
              />
              <Image
                src={flogo4}
                alt="logo"
                className="md:w-36	w-46% md:mr-3 md:mt-0 mt-5"
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
