import Head from 'next/head'
import Image from 'next/image'
import { motion } from "framer-motion"
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import aboutbanner from '/public/assets/images/aboutbanner.png'
import dots2 from '/public/assets/images/dots2.png'
import React from 'react'

const policy = () => {
  return (
<>
    <Head>
        <title> Policy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        
      </Head>

    <div>


    <main>
<div className='lg:max-w-xxxl md:max-w-xxxl mx-auto md:pl-7 pl-2 md:pr-7 pr-2 pt-28 pb-10'>
<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-6 md:text-4xl md:md:mb-2 text-4xl mb-2.5'> Privacy Policy </h2>
<h2 className='font-poppins lg:text-xl font-bold text-dark lg:mb-6 md:mb-6 md:text-4xl md:md:mb-2 text-4xl mb-2.5'>SCOPE</h2>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>At Foodgienic Innovations Private Limited, we prioritize the protection of your Personal Information. Our commitment to privacy is reflected in this comprehensive Privacy Policy. This Policy outlines our data collection practices and applies to any Personal Information we collect from you through our application and online platforms. Whether we are providing you with our Services or educating you about the Services offered, we strive to maintain the highest level of privacy and security for your information.
 Rest assured that your privacy is our top priority.</p>

 <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>Our Privacy Policies are designed to provide a clear understanding of how we collect, use, and disclose data. It&apos;s important to note that this policy does not cover any Personal Information that restaurants may collect about you. We are independent organizations, so it&apos;s recommended that you refer to our privacy policies, terms, or conditions specific to each entity in order to fully understand their practices regarding your Personal Information.</p>

 <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>By using these Services, you affirm that you have read the terms and conditions of this Privacy Policy and that you understand, agree to be bound by, and acknowledge all the terms contained herein. If you do not agree to be bound by the terms of this Privacy Policy, then do not use the Services.
CHILDREN</p>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>Our Services prioritize the safety and privacy of our users. We firmly believe in protecting children under the age of 16, which is why we do not knowingly collect or request Personal Information from them through our online platforms. If you become aware that a child has unintentionally provided us with Personal Information online, we kindly ask that you reach out to us using the instructions provided in our &quot;How To Contact Us&quot; section. Together, we can create a secure online environment for everyone.</p>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3'> TYPES OF INFORMATION WE COLLECT </h2>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>Generally, Personal Information refers to information that can identify you or has the potential to do so. This does not encompass de-identified or specific aggregate information. We gather Personal Information from you and about you, which may consist of:</p>
<ul className='list-disc pl-10'>
  <li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> <strong> Contact Information. </strong>Reaching out and staying connected is essential, which is why we value your restaurant&apos;s information. Whether it&apos;s personal or business-related, we appreciate having your restaurant or food outlet name, address, business contact number (including mobile), and email address on file. Rest assured that this information allows us to provide top-notch hygienic services tailored to your kitchen needs and ensures effective communication between us.</p>
</li>
<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '><strong> Login Credentials. </strong> Creating an account with us allows you to access our services securely and conveniently. By providing your login credentials, which consist of a username and password, you can enjoy a personalized experience tailored to your needs. Rest assured that your information will be protected, ensuring peace of mind while using our platform.</p>
</li>
<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> <strong> Technological Information. </strong> We gather technological information such as your IP address, device ID, and operating system to enhance your experience with our Services. This data helps us understand how you interact with our application and allows us to ensure the security and reliability of our systems. By monitoring visitor traffic, we can optimize the performance and integrity of our platform. Rest assured, your information is handled with utmost care. </p>
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '><strong> Internet Activity.</strong> We understand that your privacy is important to you, and we want to assure you that we respect that. As part of our commitment to transparency, we want to let you know about the information we collect. This includes your browsing history, search history, and interactions with other applications, or advertisements. However, rest assured that this information is used solely for the purpose of providing you with tailored advertising content. We believe in giving you a personalized experience that aligns with your interests. If you would like more information about our advertising practices, including targeted advertising, please refer to our &quot;How We Use Your Information&quot; and &quot;How We Share Your Information&quot; sections.</p>
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> <strong>Information You Submit.</strong> By filling out our online contact form and providing additional information in the free text box, you&apos;re taking a proactive step toward getting the information or quote you need. We appreciate your willingness to share this information with us because it allows us to respond to your request promptly and with great accuracy.</p>
</li>

</ul>


<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>Our commitment is to ensure that we retain each category of Restaurant Information for as long as it serves a purpose. Whether it&apos;s to meet legal obligations, fulfill your requests, or enhance our Services, we are dedicated to continuous improvement. We believe in the potential for growth and progress, and we remain optimistic about the positive impact our efforts can have.</p>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> HOW WE COLLECT YOUR INFORMATION</h2>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>There are multiple ways in which we gather your Personal Information. Let&apos;s take a look at some examples of how we might obtain this information on our Services.
Directly From You. </p>

<ul className='list-disc pl-10'>
  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Directly From You.  </p>
  </li>
  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Passively: Visit and navigate or, by location-based features.</p></li>

  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> From Third Parties. Through third-party sources, we may obtain Personal Information about you, provided that we have obtained your consent or as allowed by applicable law. These other sources may include</p>

<ul className='list-disc pl-10'>
<li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Our service providers, include data analytics providers, internet service providers, operating systems and platforms, and online advertising networks.
 </p></li>

<li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Social media sites, such as Facebook, Twitter, YouTube, LinkedIn, and Instagram. </p></li>
</ul>
</li>
<li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> <strong> By Combining Information. </strong> </p></li>

  <ul className='list-disc pl-10'>
<li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>Aggregate the personal information gathered offline with the data collected through our Services.
 </p></li>

 <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Consolidate the personal information obtained about you from various devices used to access our services.
 </p></li>
<li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>Merge the personal information acquired from third parties with the existing data we possess about you. </p></li>
</ul>

</ul>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
HOW WE USE YOUR INFORMATION </h2>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Examples of how we may use the Personal Information that we collect through our Services include:
 </p>
<ul className='list-decimal pl-10'>
<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>  Our primary goal is to provide our client with exceptional services. Your satisfaction is important to us, and we strive to fulfill all of your requests efficiently and effectively.
 </p>
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>  We are constantly working towards improving our services, and we may use your personal information to enhance your overall experience with us. Through customization, we can tailor our services to better suit your individual needs.
 </p>
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>  Understanding your interests is essential for us to provide you with a personalized experience. By analyzing your personal information, we gain valuable insights into the features of our services that appeal to you the most.
 </p>
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Promptly responding to your requests or inquiries is a top priority for us. Whether it&apos;s addressing feedback, providing quotes, or supplying additional information, we are here to assist you every step of the way.
 </p>
</li>


<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Communication plays a vital role in maintaining a strong relationship with our clients. We will keep you informed about any relevant updates regarding your account or changes in the privacy policy which may affect you.As part of our marketing efforts, we may use your personal information to present targeted advertising that aligns with your preferences and interests. These advertisements may include third-party offers for tools, products, or services that we believe will capture your attention.
 </p>
</li>


<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>  As part of our marketing efforts, we may use your personal information to present targeted advertising that aligns with your preferences and interests. These advertisements may include third-party offers for tools, products, or services that we believe will capture your attention.
 </p>
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>  Ensuring the security of both our company and our clients is of utmost importance to us. This includes safeguarding against potential risks and threats not only on this application but also within all aspects of our services.
 </p>
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>  As permitted by law and in compliance with legal requirements, there may be instances where we utilize or disclose personal information for purposes not explicitly stated above.
 </p>
</li>

</ul>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Please note that any further notifications regarding the use or disclosure of personal information will be provided accordingly as necessary.
 </p>

 <h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
 HOW WE SHARE YOUR INFORMATION</h2>

 <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> We may share your Personal Information in the following ways:
 </p>
<ul>
  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Your Restaurant Information may be displayed or reposted on our Services or Social Media Pages. 
  This can include information that you post in our social media forums such as Facebook, Twitter, YouTube, LinkedIn, and Instagram.
 </p>
  </li>

  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> We may also share your Restaurant Information with third-party
   service providers who perform services on our behalf. This could include payment processors and companies that send emails on our behalf, as well as operating systems or platforms that assist us
    in running our Services.
 </p>
  </li>


  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Data analytics providers play a crucial role in targeted advertising by collecting and analyzing Restaurant Information from users across various applications, and devices. This may include our own web application, where third-party data analytics providers also collect such information. It is important to note that these practices could be deemed as a &quot;sale&quot; of Restaurant Information under certain state laws. To learn more about your options pertaining to these communications, please refer to the section on Choices Regarding Your Information.
 </p>
  </li>

  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Additionally, we collaborate with our trusted business partners, including restaurants and food outlets, to enhance our services and offerings.
In the event that we merge with, acquire, or are acquired by another business entity, or sell a brand or part of our business, we may transfer customer information, including your Restaurant Information. This could occur through an asset sale, corporate reorganization, or other change of control, potentially involving the bankruptcy process. Your consent to such transfers is hereby granted and we may assign and transfer all rights, benefits, duties, and obligations of this Privacy Policy as described in this paragraph.
 </p>
  </li>

  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>In the event that we merge with, acquire, or are acquired by another business entity, or sell a brand or part of our business, we may transfer customer information, including your Restaurant Information. This could occur through an asset sale, corporate reorganization, or other change of control, potentially involving the bankruptcy process. Your consent to such transfers is hereby granted and we may assign and transfer all rights, benefits, duties, and obligations of this Privacy Policy as described in this paragraph.
 </p>
  </li>

  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> In order to comply with the law and protect ourselves, there are instances where we may need to share your restaurant information. This could include responding to a court order or subpoena, or if requested by a government agency or investigatory body. Additionally, we may share personal information to protect our own legal rights, such as working with third-party accountants or outside legal counsel. Our priority is to ensure the rights, privacy, safety, and property of ourselves, our employees, and personnel associated with us, our business partners, and you.
 </p>
  </li>

  <li>
  <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> We will only use your restaurant information for other purposes if you provide consent. We also reserve the right to share restaurant information for reasons that we may describe specifically to you. Your trust and privacy are important to us, which is why we handle your restaurant information responsibly and transparently.
 </p>
  </li>

</ul>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
CHOICES REGARDING YOUR INFORMATION </h2>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Users have the option to make choices regarding the usage of their Restaurant Information. These choices are specific to the browser and/or device being used.
 </p>

 <h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
 Marketing Communications </h2>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> If you would prefer not to receive our marketing communications, it is possible to opt out. However, please keep in mind that you will continue to receive transactional messages from us. These messages include important information about your account and any responses to your inquiries. To initiate the opt-out process for our marketing communications, simply follow the instructions provided with each communication you receive.
 </p>


 <h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
 Cookies & Other Tracking Technologies:</h2>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> As you browse the internet, web applications and websites utilize small text files known as cookies. These cookies are stored by your web browser and serve multiple purposes. In addition to cookies, pixel tags, web beacons, and other tracking technologies are employed to better understand your interaction with this application. For a more comprehensive explanation, please refer to the &quot;How We Use Your Information&quot; section above. 
 </p>
 <p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> Cookies and tracking technologies play crucial roles by storing specific data that enable important functions. However, if you would rather not share this data, you have the option to disable cookies. It&apos;s important to note that disabling cookies may result in some inconvenience when using our services. While our application does not support the complete deactivation of all described tracking technologies in this section, you can choose to opt out of targeted advertising by following the instructions provided in the section below titled &quot;Rights Regarding Personal Information.&quot;
</p>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>You have the option to manage cookies and tracking tools through your web browser. The method may vary depending on the specific tool you are using. If you prefer not to have information collected, including Restaurant Information, through cookies, most browsers offer a straightforward process to automatically decline or choose whether to accept or decline the transfer of specific cookies from applications onto your computer.
</p>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
RIGHTS REGARDING PERSONAL INFORMATION</h2>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>
Individuals may have certain rights, referred to as Data Subject Rights, in relation to the Personal Information collected or processed by us. These rights may vary depending on your place of residence, but we strive to uphold them regardless. It is important to note that we reserve the right to comply with your Data Subject Rights as mandated by relevant legislation.
</p>
<ul className='list-decimal pl-10'>
<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>
<strong>Right to Access and Obtain a Copy:</strong> Upon your request, we can provide you with a confirmation of whether we are processing your Personal Information and furnish you with a copy of all the Personal Information that you have a lawful entitlement to receive, together with pertinent additional information. Moreover, if you desire, we can disclose the types of third parties with whom we share your Personal Information and outline the specific categories of Personal Information that we share with them.
</p>
  
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>
<strong>Right to Amend:</strong> The Right to Amend allows you to request corrections or completion of any inaccurate or incomplete Personal Information. If you reach out to us, and it is both possible and lawful, we will also provide you with the information about any third parties with whom your Personal Information was shared, so you can directly contact them.
</p>
  
</li>


<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>
<strong> Right to Delete: </strong> You have the right to request the deletion of your Personal Information. If we have shared your Personal Information with others, we will inform them of the erasure in accordance with legal requirements.
</p>
  
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>
<strong>Right to Restrict Processing:</strong> You have the right to request that we limit or suspend the processing of your Personal Information under certain circumstances. This may include situations where we handle sensitive Personal Information in accordance with state laws or engage in automated decision-making processes.
Right to Opt-Out of Targeted Advertising: Targeted advertising is a commonly used method of delivering customized advertisements to individuals based on their Personal Information collected from various businesses, websites, applications, or services. It is important to note that you have the right to choose whether or not to participate in this practice. You can opt out of targeted advertising if you so desire.
</p>
  
</li>

<li>
<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>

<strong>Right to Non-discrimination:</strong> We are committed to upholding your rights and will not engage in any form of discrimination for exercising them. However, please note that there may be a reasonable fee as allowed by law for fulfilling these rights. For instance, if you request multiple copies of your Personal Information, a charge may apply. Rest assured, we are dedicated to ensuring transparency and compliance with applicable regulations.
</p>
  
</li>

</ul>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
SECURITY AND RETENTION </h2>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>

We have implemented a comprehensive set of measures, including administrative, physical, and technological safeguards, to protect the Personal Information that we control. However, it is important to understand that no data transmission or storage system can guarantee complete security. If you suspect that the security of your communication with us has been compromised, such as unauthorized access to your account, we kindly request that you promptly notify us by following the instructions provided in our How To Contact Us section.
</p>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>

Furthermore, please note that certain laws may require us to disclose your information to government agencies, courts, law enforcement authorities, or regulatory bodies. It is essential to be aware that if you are using our Services outside of India and accessing this web application, your Personal Information will be transmitted to our servers located in India. This transmission is necessary for providing you with the information you requested and administering our Services properly as outlined in this Privacy Policy.
</p>


<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
LINKS </h2>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>

This Privacy Policy does not cover, and we do not assume responsibility for, the privacy or information practices of any third parties, including those operating sites or services linked to our own. The inclusion of a link on our platform does not indicate our endorsement of that particular site or service. Furthermore, we are not accountable for the policies or practices related to the collection, usage, disclosure, or security of information by other organizations such as Facebook, Apple, Google, Microsoft, LinkedIn, app developers or providers, social media platforms providers, operating system providers, 
wireless service providers or device manufacturers. This includes any Personal Information you provide to these organizations through our Services.
</p>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
HOW TO CONTACT US </h2>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>

If you have any inquiries, feedback, or apprehensions regarding our privacy practices or this Policy, if you wish to update your information, or if you would like to exercise your Data Subject Rights, please do not hesitate to reach out to us at support@foodgienic.com or at 7814606432.
</p>

<h2 className='font-poppins lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 
CHANGES IN POLICY </h2>

<p className='font-montserrate xl:text-lg lg:text-base lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>

From Time to time, our Privacy Policy may undergo modifications. By law, we are obligated to inform you of any significant changes. Additionally, an updated version will be available on our application. Please note that the present Privacy Policy is accurate as of the date indicated at the top of this page.
</p>


</div>

      </main>
    </div>
    </>
  )
}

export default policy
