import Head from 'next/head'
import Image from 'next/image'
import { motion } from "framer-motion"
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import aboutbanner from '/public/assets/images/aboutbanner.png'
import dots2 from '/public/assets/images/dots2.png'
import React from 'react'

const terms = () => {
  return (
    <>

     <Head>
        <title> Terms </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        
      </Head>
    
    <div>
      <main>
    <div className='lg:max-w-xxxl md:max-w-xxxl mx-auto md:pl-7 pl-2 md:pr-7 pr-2 pt-28 pb-10'>
<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-6 md:text-4xl md:md:mb-2 text-4xl mb-2.5'>Terms and Conditions for Foodgienic Innovations Private Limited</h2>
<p className='font-montserrate xl:text-lg lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>Please read these terms and conditions carefully before using the services provided by Foodgienic Innovations Private Limited (&quot;Foodgienic,&quot; &quot;we,&quot; or &quot;us&quot;). These terms and conditions outline the rights and obligations of Foodgienic and its customers (&quot;you&quot; or &quot;customer&quot;) in relation to the hygienic services provided to commercial kitchens. By using our services, you agree to comply with and be bound by these terms and conditions. 
If you do not agree with any part of these terms and conditions, you must not use our services.</p>

<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3'> 1. Definitions </h2>
<ul className='list-disc pl-10'>
 <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>&quot;Foodgienic&quot; is the term used to refer to the company itself, Foodgienic Innovations Private Limited. This is the legal entity that provides the services mentioned in the content.</p>
  </li>

  <li>
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> &quot;Services&quot; refers to the specific hygienic services that Foodgienic offers to commercial kitchens. These services are designed to maintain and enhance the cleanliness and hygiene standards of the kitchen facilities. Examples of such services may include deep cleaning, sanitization, pest control, waste management, or any other activities that contribute to maintaining a clean and hygienic environment.</p>
</li>

<li>
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> 
    &quot;Customer&quot; refers to any individual or entity that engages with Foodgienic&apos;s services. In this context, it refers to those who contract with Foodgienic to avail their hygienic services for their commercial kitchens. Customers can range from small restaurants and cafes to larger food establishments and catering companies.</p>
</li>
<li>
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> 
    &quot;Commercial Kitchen&quot; refers to any facility or establishment involved in the preparation, cooking, or serving of food for commercial purposes. This can include restaurants, hotels, cafes, canteens, catering businesses, or any other similar food service establishments. Foodgienic&apos;s services are specifically tailored to cater to the needs of such commercial kitchens, ensuring that they adhere to proper hygiene standards and regulations.</p>
</li>

</ul>

<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 2. Service Agreement </h2>

<ul className='list-disc pl-10'>
 <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>By engaging Foodgienic&apos;s services, the customer acknowledges and agrees to be bound by the terms and conditions outlined in the agreement. This means that the customer accepts and agrees to abide by the rules and regulations specified in the document.</p>
  </li>

  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Foodgienic will provide hygienic services to the customer&apos;s commercial kitchen based on the agreed terms and conditions. The specific services to be provided will be determined through mutual agreement between Foodgienic and the customer. This clause ensures that both parties are aware of the services that will be delivered and that they are in agreement on the scope of work.</p>
  </li>

  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>The customer is responsible for providing accurate and complete information about their commercial kitchen to Foodgienic. This information is necessary for Foodgienic to effectively deliver hygienic services. Accurate details regarding the size, layout, equipment, occupancy, and specific requirements of the kitchen will enable Foodgienic to tailor their services accordingly.</p>
  </li>

  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>The customer agrees to comply with all applicable laws, regulations, and industry standards related to hygiene and food safety. This clause emphasizes the importance of legal and regulatory compliance for the customer&apos;s commercial kitchen. It ensures that the customer operates their kitchen in accordance with the necessary standards and guidelines to maintain hygiene, storage, a healthy environment, and food safety practices.</p>
  </li>


</ul>


<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'>3. Scope of Services </h2>

<ul className='list-disc pl-10'>
 <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>By engaging Foodgienic&apos;s services, the customer acknowledges and agrees to be bound by the terms and conditions outlined in the agreement. This means that the customer accepts and agrees to abide by the rules and regulations specified in the document.</p>
  </li>

  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>The services provided by Foodgienic may include a range of activities designed to maintain the cleanliness and hygiene of commercial kitchens. These services are not limited to specific tasks but can encompass various activities such as deep cleaning of kitchen equipment, cleaning of exhaust systems, pest control measures, sanitization procedures, and general maintenance. This indicates that Foodgienic offers a comprehensive set of services to address different aspects of maintaining a hygienic environment in commercial kitchens.</p>
  </li>

  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Foodgienic commits to using its best efforts to ensure the quality and effectiveness of the services provided. However, it is important to note that the complete elimination of all contaminants cannot be guaranteed. This clause sets a realistic expectation for the customer, acknowledging that while Foodgienic strives for high standards, certain factors beyond their control may impact the complete elimination of contaminants. It emphasizes the importance of regular maintenance and ongoing efforts to maintain hygiene in commercial kitchens.</p>
  </li>

  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Foodgienic reserves the right to subcontract or engage third parties to provide certain services as deemed necessary. This clause gives Foodgienic the flexibility to collaborate with other service providers or experts to fulfill specific requirements of the customer. It allows Foodgienic to leverage specialized skills or resources when needed to deliver the services effectively.</p>
  </li>

  </ul>

  <h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 4. Payment Terms </h2>

  <ul className='list-disc pl-10'>

 <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> The customer agrees to pay the fees for the services provided by Foodgienic as agreed upon in the service agreement. This implies that there is a mutual understanding between Foodgienic and the customer regarding the fees associated with the services. The specific fee structure and amounts will be detailed in the service agreement.</p>
  </li>
  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> The payment terms, including the frequency of invoicing and acceptable methods of payment, will be clearly specified in the service agreement. This ensures that both parties have a clear understanding of when and how payments should be made. The agreement will outline whether payments are due monthly, quarterly, or based on another agreed-upon schedule. It will also specify the accepted methods of payment, such as bank transfers, checks, or online payment platforms.<br></br>
    With this agreement, both parties have agreed to adhere to the on-time payment policy. Foodgenice kindly requests that payment be made within 15 days of the invoice being generated. Failure to meet this deadline may result in per day penalty being imposed.<br></br>
    In the event of non-payment or late payment, Foodgienic reserves the right to suspend, or impose plenty of the services until payment is received in full. This clause emphasizes the importance of timely payment. If the customer fails to make the necessary payments as outlined in the service agreement, Foodgienic has the right to temporarily suspend or completely terminate the services until the outstanding payments are settled. This clause protects Foodgienic&apos;s business interests and ensures that they are compensated for the services provided.</p>
  </li>
</ul>

<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 5. Cancellation and Termination </h2>
  <ul className='list-disc pl-10'>

  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Either party, Foodgienic or the customer, has the right to terminate the service agreement by providing written notice to the other party. This clause allows either party to initiate the termination process by formally communicating their intent to terminate the agreement in writing. The notice period for termination may be specified within the agreement itself.</p>
  </li>
  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>In the event of termination, the customer agrees to pay any outstanding fees for services rendered up to the termination date. This implies that even after termination, the customer remains responsible for any fees owed to Foodgienic for the services provided up until the termination becomes effective. The customer is obligated to settle any outstanding payments promptly.</p>

  </li>
  <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Foodgienic reserves the right to terminate the services immediately, without prior notice, in certain circumstances. These circumstances include non-compliance with the terms and conditions outlined in the agreement or if the customer&apos;s commercial kitchen poses a risk to the health and safety of Foodgienic&apos;s employees or other customers. This clause provides Foodgienic with the authority to terminate the services immediately if the customer fails to comply with the agreed-upon terms or if there are concerns regarding the safety of Foodgienic&apos;s employees or other customers. It prioritizes the well-being and safety of all parties involved.</p>

  </li>
  </ul>

  <h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 6. Intellectual Property </h2>

  <ul className='list-disc pl-10'>

 <li> 
    <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>All intellectual property rights, including trademarks, logos, and copyrighted material, associated with Foodgienic&apos;s services, remain the property of Foodgienic. This clause establishes that Foodgienic is the rightful owner of its intellectual property. This intellectual property can include elements such as the company&apos;s trademarks, logos, branding materials, copyrighted content, or any other creative works associated with its services.<br></br>
The customer agrees not to use, reproduce, modify, or distribute Foodgienic&apos;s intellectual property without prior written consent. This clause specifies that the customer is not granted any rights to use, reproduce, modify, or distribute Foodgienic&apos;s intellectual property without obtaining prior written permission from Foodgienic. It restricts the customer from engaging in any unauthorized use or exploitation of Foodgienic&apos;s intellectual property.</p>
  </li>
  
  </ul>


  <h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 7. Limitation of Liability </h2>

<ul className='list-disc pl-10'>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Foodgienic specifies that it will not be held responsible for any direct, indirect, incidental, consequential, or exemplary damages that may arise from the provision of its services. This includes damages such as loss of profits, business interruption, or reputational harm. The clause clarifies that Foodgienic cannot be held liable for any financial, operational, or reputational losses experienced by the customer as a result of using Foodgienic&apos;s services. It recognizes that there are inherent risks involved in the services provided.</p>
</li>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Foodgienic&apos;s liability, if applicable, is limited to the total amount paid by the customer for the services rendered. This means that if Foodgienic is found to be liable for any damages, its liability will be capped at the total amount paid by the customer for the specific services provided. This clause sets a financial limit to Foodgienic&apos;s potential liability, safeguarding the company from excessive financial obligations. </p></li> 
 <li> <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>We would like to clarify that as a service provider, Foodgenic cannot be held responsible for the hygiene of your food. Any issues related to the cleanliness or quality of food in your restaurant or food outlet are not under our jurisdiction. Please understand that our services are focused on other aspects of your business..</p>
</li>

</ul>

<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 8. Confidentiality </h2>

<ul className='list-disc pl-10'>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Both parties, Foodgienic, and the customer, agree to maintain the 
  confidentiality of any proprietary or sensitive information disclosed during the provision of the services. This clause establishes a mutual obligation for both parties to keep such information confidential. 
  It includes any proprietary or sensitive information shared during the course of the service agreement, ensuring that both parties respect the confidentiality and privacy of such information.<br></br>
Foodgienic states that it may collect and process personal data in accordance with its Privacy Policy. The Privacy Policy, which is available on Foodgienic&apos;s website, 
outlines how personal data is collected, used, stored, and protected by the company. 
This clause informs the customer that Foodgienic may handle their personal data and directs them to review the Privacy Policy for detailed information on how their data is managed.</p>
</li>

</ul>

<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 9. Governing Law and Jurisdiction </h2>

<ul className='list-disc pl-10'>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>These terms and conditions shall be governed by and construed in accordance with the laws of the jurisdiction where Foodgienic is registered. This clause establishes that the laws of the specific jurisdiction where Foodgienic is registered will govern the interpretation and enforcement of the terms and conditions outlined in the agreement. It ensures that any legal matters or disputes related to the agreement will be determined based on the laws of that jurisdiction.<br></br>
Any dispute arising out of or in connection with these terms and conditions shall be subject to the exclusive jurisdiction of the courts or arbitrations in the aforementioned jurisdiction. This clause specifies that any disputes or legal proceedings arising from the agreement will be exclusively resolved by the courts in the jurisdiction mentioned above. It establishes the jurisdiction in which any legal actions or disputes will be heard and resolved. In case a dispute has been settled through arbitration both the parties are liable to pay the fees & expenditure of the arbitrator.</p>
</li>

</ul>


<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 10. Amendments </h2>

<ul className='list-disc pl-10'>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Foodgienic reserves the right to modify these terms and conditions at any time. This clause grants Foodgienic the authority to make changes to the terms and conditions of the service agreement. It acknowledges that Foodgienic may need to update or revise the terms and conditions to reflect changes in its business, industry regulations, or other relevant factors.<br></br>
Any modifications to these terms and conditions will be effective upon posting on Foodgienic&apos;s website or providing notice to the customer. This clause outlines the methods through which the modifications to the terms and conditions will be communicated and become effective. It states that modifications may be posted on Foodgienic&apos;s website or provided to the customer directly through notice. Once the modifications are communicated through these means, they will become effective.</p>
</li>

</ul>



<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-3 md:text-4xl md:md:mb-2 text-4xl mb-3 mt-11'> 11. Entire Agreement </h2>

<ul className='list-disc pl-10'>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>These terms and conditions constitute the entire agreement between Foodgienic and the customer regarding the provision of services. This clause states that the terms and conditions outlined in the agreement represent the complete and comprehensive agreement between Foodgienic and the customer. It specifies that these terms and conditions supersede any prior agreements or understandings, whether written or oral, related to the provision of services by Foodgienic.<br></br>
By using Foodgienic&apos;s services, you acknowledge that you have read, understood, and agreed to these terms and conditions. If you have any questions or concerns, please contact Foodgienic for further clarification.</p>
</li>

</ul>


<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-6 md:text-4xl md:md:mb-2 text-4xl mb-2.5 mt-10'>Shipping and Delivery </h2>
<p className='font-montserrate xl:text-lg lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '>At Foodgienic, we understand the importance of timely and reliable shipping and delivery services in the food industry. As a leading hygienic service provider for restaurants and other food outlets&apos; kitchens, we prioritize the safe and efficient transportation of our products.</p>

<ul className='list-decimal pl-10'>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Fast and Secure Shipping: We strive to process and ship orders as quickly as possible. Once you place an order with Foodgienic, our dedicated team will carefully pack your items to maintain their hygiene and integrity during transit. We partner with trusted logistics providers who specialize in food transportation to ensure that your order reaches you in excellent condition.</p>
</li>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Nationwide Coverage: We offer nationwide shipping to cater to our customers across various locations. Whether you are running a restaurant in a bustling city or a remote town,
   we will make sure your order reaches you promptly and efficiently.</p>
</li>
<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Tracking and Updates: We provide real-time tracking information for all shipments, allowing you to stay informed about the progress of your order. You will receive regular updates via email or SMS, enabling you to plan accordingly and have complete visibility into the shipping process.</p>
</li>
<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Quality Packaging: Maintaining hygiene is paramount to Foodgienic. We use high-quality packaging materials, including food-grade containers and sealed bags, to ensure that your products remain fresh and contamination-free during transit. Our packaging is designed to withstand transportation challenges, such as temperature fluctuations while safeguarding the integrity of the items.</p>
</li>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Timeframe: It will take </p>
</li>


</ul>

<h2 className='font-montserrate lg:text-2xl font-bold text-dark lg:mb-6 md:mb-6 md:text-4xl md:md:mb-2 text-4xl mb-2.5 mt-10'> Refund Policy </h2>
<p className='font-montserrate xl:text-lg lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-6 md:text-sm md:leading-7 text-sm leading-7 '> At Foodgienic, we are committed to providing exceptional services to our customers. If, for any reason, you are not satisfied with our services, we have a comprehensive refund policy in place to address your concerns. </p>


<ul className='list-decimal pl-10'>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '>Eligibility: To be eligible for a refund, you must reach out to our customer support team within a month, typically. </p>
</li>

<li> 
  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Valid Reasons for Refunds: Refunds may be granted in cases where there is a discrepancy in the services, such as improper hygiene of your kitchen or if our services do not meet the expected quality standards.  </p>
</li>

<li> 

  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Valid Reasons for Refunds: Refunds may be granted in cases where there is a discrepancy in the services, such as improper hygiene of your kitchen or if our services do not meet the expected quality standards.  </p>
</li>
<li> 

  <p className='font-montserrate lg:text-base xl:text-lg lg:leading-8 text-dark leading-8 mb-2 md:text-sm md:leading-7 text-sm leading-7 '> Customer Satisfaction: Your satisfaction is of utmost importance to us. If you have any concerns or questions regarding our refund policy, our dedicated customer support team is available to assist you and address any queries you may have.<br></br>
  
  Customer Satisfaction: Your satisfaction is of utmost importance to us. If you have any concerns or questions regarding our refund policy, our dedicated customer support team is available to assist you and address any queries you may have. </p>
</li>

</ul>

     </div>

      </main>
    </div>
    


   </ >
  )
}

export default terms
