import Head from 'next/head'
import Image from 'next/image'
import { motion } from "framer-motion"
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import aboutbanner from '../../../../public/assets/images/aboutbanner.png'
import user from '../../../../public/assets/images/user.png'
import dots2 from '/public/assets/images/dots2.png'
import axios from 'axios'
import Cookies from 'js-cookie'

import { useDispatch, useSelector } from 'react-redux'
import { useEffect } from 'react'
import { getAllBlogData, getBlogFunc } from '@/app/auth/store/Slices/BlogSlice'
import moment from 'moment/moment'
import { useRouter } from 'next/router'


console.log("aboutbanner", aboutbanner)
const inter = Inter({ subsets: ['latin'] })

export default function Pricing() {
  const dispatch = useDispatch()
  const selecter = useSelector(getAllBlogData)

  const router = useRouter()
  console.log("selecterData", selecter)
  let blogGetData = selecter
  console.log("blogGetData>>>>>>>>>", blogGetData)
  useEffect(() => {
    getApi()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const getApi = async () => {
    const data = await dispatch(getBlogFunc())
    console.log("getBlogData", data)
  }

  const perticularBlogFunc = (ele) => {
    router.push(`/main/blog-detail/${ele?.title}`)
  }


  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        <script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
      </Head>
      <main>


        <section className='md:bg-right  md:bg-no-repeat 2xl:bg-924 xl:bg-680 lg:bg-590 md:bg-460 relative xl:py-48 md:py-48	py-14 services-image bg-about-banner'>
          <div className='lg:max-w-xxxl md:max-w-xxxl mx-auto md:pl-7 pl-2 md:pr-7 pr-2'>
            <div className='flex flex-wrap items-center	justify-between relative'>
              <div className='lg:w-5/12	md:w-5/12'>
                <h1 className='font-poppins xl:text-6xl font-bold text-dark lg:mb-6 md:mb-2 mb-2.5 md:text-4xl lg:text-5xl text-3xl relative lg:before:content-[attr(before)] before:absolute before:bg-blog-text xl:before:h-48 md:before:h-28 before:h-16 md:before:w-80 sm:before:w-56 before:w-48 before:bg-10% before:bg-no-repeat before:-z-10 md:before:-top-6 sm:before:-top-8 before:-top-6 lg:before:-left-2 md:before:left-0'>Blog</h1>
                <p className='font-poppins lg:text-xl text-sm md:text-lg font-medium text-dark lg:leading-9 md:leading-8 leading-6 mb-6 text-sm'>Foodgienic is the symbol of hygienic food. Our mission is to authenticate all commercial kitchens in India. So every meal outside your home is Hygienic, Nutritious, and Delicious. Just look for our authentication on restaurants and enjoy.</p>
              </div>
              <div className='lg:w-7/12 md:w-7/12 relative z-10 md:hidden lg:-mr-3.5	-mr-2'>

              </div>

            </div>
          </div>
        </section>

        <section className='relative xl:pt-64	xl:pb-36 xl:py-20 md:pt-40 md:pb-20 md:pt-16 pt-28 pb-20 bg-aboutbg bg-contain bg-no-repeat bg-repeat'>
          <div className='lg:max-w-xxxl md:max-w-xxxl mx-auto  pl-7'>
            <h2 className='font-poppins xl:text-6xl lg:text-5xl md:text-4xl font-bold text-dark lg:mb-20 md:mb-10 text-center z-10 text-4xl mb-8'>Latest Post</h2>



            <div className='flex flex-wrap relative'>
              {blogGetData && blogGetData.length > 0 && blogGetData.map((ele, index) => {
                return (
                  <Link
                    href={{
                      pathname: `/main/blog-detail/${ele?.id}`
                    }}

                    key={index} className='md:w-2/6 md:px-2.5 w-full mb-5 sddasdadadasd'
                  >
                    <div className='bg-white rounded-xl	p-3.5 shadow-1'>
                      <div className='relative z-10 rounded-md overflow-hidden'>
                        <Image
                          alt="Logo"
                          src={ele?.image}
                          height={288}
                          width={449}
                          className='w-full rounded-t-xl h-64	object-cover'
                        />
                      </div>
                      <div className='py-5'>
                        <h3 className='bg-grey3 text-lightgrey text-base inline-block	rounded-lg font-semibold	px-3 py-1.5 blog-list-heading'>{ele?.title}</h3>
                        <p className="font-poppins font-medium text-dark text-base leading-6 text-sm line-clamp-3 mb-0.5 mt-3 list-blog-text" dangerouslySetInnerHTML={{ __html: ele?.description }}></p>
                        <Link href={{pathname: `/main/blog-detail/${ele?.id}`}} className='md:w-2/6 w-full mb-5 text-orange text-sm underline	'> Read More </Link>
                        <div className='flex items-center mt-3'>
                          <div className='flex items-center	mr-5'>
                            <Image src={user} alt='user' width={10} height={10} className='rounded-full h-9	w-9	object-cover mr-2' />
                            <h4 className='text-grey4 text-sm	font-medium	'>Tracey Wilson</h4>
                          </div>
                          <p className='text-sm text-grey4 font-poppins'> {moment(ele?.updatedAt).format('DD-MM-YYYY')}</p>
                        </div>
                      </div>

                    </div>
                  </Link>
                )
              })}
            </div>




            <div className='absolute left-0	xl:-top-28 md:-top-20 -left-1.5	hidden md:block'>
              <Image
                alt="Dots"
                src={dots2}
                className='md:w-3/5 xl:w-full md:mr-auto md:w-10/12 xl:m-0'
              />
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
