import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import leave1 from "/public/assets/images/leave1.svg";
import leave2 from "/public/assets/images/leave2.svg";
import dots from "/public/assets/images/dots.png";
import dots2 from "/public/assets/images/dots2.png";
import dots3 from "/public/assets/images/dots3.png";
import * as Yup from "yup";
// import {serviceData} from '../../../common/PagesContent'

import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import {
  getAllDynamicData,
  getServiceData,
} from "@/app/auth/store/Slices/DynamicContentSlice";
import { ErrorMessage, Field, Form, Formik } from "formik";
const inter = Inter({ subsets: ["latin"] });

export default function Services() {
  // console.log("serviceData",serviceData)
  const [branding, setBranding] = useState(false);
  const [assured, setassured] = useState(false);
  const [software, setSoftware] = useState(false);
  const [hygiene, setHygiene] = useState(false);
  const [Standard, setStandard] = useState(false);
  const [Cost, setCost] = useState(false);

  const validationSchema = Yup.object().shape({
    firstname: Yup.string().required("  First name is required"),
    lastName: Yup.string().required(" Last name is required"),
    email: Yup.string().email("Invalid email").required(" Email is required"),
  });

  const dispatch = useDispatch();
  const selecter = useSelector(getServiceData);
  let serviceData = [];
  serviceData.push(selecter);

  useEffect(() => {
    getApi();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const getApi = async () => {
    const data = await dispatch(getAllDynamicData());
    console.log("getAboutData", data);
  };

  const readMoreBrandingHandler = () => {
    setBranding(!branding);
  };
  const readMoreAssuredHandler = () => {
    setassured(!assured);
  };
  const readMoreSoftwareHandler = () => {
    setSoftware(!software);
  };
  const readMoreHygieneHandler = () => {
    setHygiene(!hygiene);
  };
  const readMoreStandardHandler = () => {
    setStandard(!Standard);
  };
  const readMoreCostHandler = () => {
    setCost(!Cost);
  };

  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        {serviceData &&
          serviceData.length > 0 &&
          serviceData.map((ele, index) => {
            return (
              <div key={index}>
                <section
                  className="md:bg-right  md:bg-no-repeat 2xl:bg-924 xl:bg-680 lg:bg-590 md:bg-460 relative xl:py-48 md:py-48	py-14 services-image"
                  style={{
                    backgroundImage:
                      "url(" + ele.service_First_Section.first_Img + ")",
                  }}
                >
                  <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto md:pl-7 pl-2 md:pr-7 pr-2">
                    <div className="flex flex-wrap items-center	justify-between relative">
                      <div className="lg:w-5/12	md:w-5/12">
                        <h1 className="font-montserrate xl:text-6xl font-bold text-dark lg:mb-6 md:mb-2 mb-2.5	md:text-4xl lg:text-5xl text-3xl relative lg:before:content-[attr(before)] before:absolute before:bg-servicetext before:h-16 xl:before:w-38r md:before:w-96 md:before:h-28 before:w-72 before:bg-10%	before:bg-no-repeat	before:-z-10 md:before:-top-2 before:-top-2 before:left-0">
                          {ele.service_First_Section.first_title}
                        </h1>
                        <p className="font-montserrate lg:text-xl text-sm md:text-lg font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark mb-6">
                          {ele.service_First_Section.first_descriptions}
                        </p>
                      </div>
                      <div className="lg:w-7/12 md:w-7/12 relative z-10 md:hidden lg:-mr-3.5	-mr-2">
                        <Image
                          alt="Service Banner"
                          width={100}
                          height={100}
                          src={ele.service_First_Section.first_Img}
                        />
                      </div>
                    </div>
                  </div>
                </section>

                <section className="bg-grey lg:pt-32	bg-center	bg-100% bg-no-repeat md:pt-28 md:pt-32 m:pb-0	md:pt-40 pb-0 pt-10 mt-1 relative">
                  <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
                    <h2 className="font-montserrate xl:text-6xl lg:text-5xl md:text-4xl font-bold text-dark text-center z-10 relative lg:before:content-[attr(before)] before:absolute before:bg-servicetext before:h-16 xl:before:w-38r md:before:w-96 md:before:h-28 before:w-72 before:bg-10%	before:bg-no-repeat	md:before:-top-2 before:-top-2 before:-left-2.5 before:right-0 before:left-0	before:mx-auto before:-z-10 text-4xl	mb-8">
                      {ele.service_Second_Section.Second_title}
                    </h2>
                    <p className="font-montserrate lg:text-lg text-sm md:text-base font-medium text-dark lg:leading-9 md:leading-8 leading-6 text-dark text-center lg:max-w-5xl mx-auto">
                      {ele.service_Second_Section.Second_descriptions}
                    </p>
                  </div>
                  <div className="absolute left-0 xl:-top-28 md:-top-20 -left-1.5 hidden md:block">
                    <Image
                      alt="Dots"
                      src={dots2}
                      className="md:w-3/5 xl:w-full md:mr-auto md:w-10/12	 xl:m-0"
                    />
                  </div>
                </section>

                {ele &&
                  ele.service_Second_Section &&
                  ele.service_Second_Section.Second_service_Types_section.map(
                    (element, index) => {
                      return (
                        <section
                          key={index}
                          className="odd:bg-grey even:bg-white	bg-center	bg-100% bg-no-repeat md:pt-32 md:pb-32 pb-10 pt-10 relative direction-row-class"
                        >
                          <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 pl-2 md:pr-7 pr-2">
                            <div className=" md:relative">
                              <div className="flex flex-wrap items-center	justify-between direction-row-inner">
                                <div className=" lg:w-6/12	md:w-6/12 md:pr-6 service-text">
                                  <h3 className="font-montserrate xl:text-4xl lg:text-3xl font-bold text-dark lg:mb-6 md:mb-6 relative md:text-4xl md:md:mb-2 text-4xl mb-2.5">
                                    {element.st_title}
                                  </h3>
                                  <p className="font-montserrate lg:text-lg text-sm md:text-base font-medium text-dark lg:leading-8 md:leading-7 leading-6 text-dark mb-6">
                                    {element.st_descriptions}
                                  </p>
                                </div>
                                <div className=" lg:w-6/12 md:w-6/12 md:pl-6 service-img">
                                  <div className="  p-1 md:mt-0	mt-8">
                                    <div className="overflow-hidden relative md:h-466 rounded-lg">
                                      <Image
                                        alt="Service"
                                        height={466}
                                        width={675}
                                        src={element.st_Img}
                                        className="object-cover h-full w-full sm:ease-in sm:duration-700 sm:hover:h-550 sm:hover:w-550"
                                      />
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </section>
                      );
                    }
                  )}
              </div>
            );
          })}

        <section className="lg:pt-24 xl:pb-20	md:pb-24 relative md:pt-16 pt-28 pb-20">
          <div className="lg:max-w-xxxl md:max-w-xxxl mx-auto  md:pl-7 md:pr-7 pr-4 pl-4 relative">
            <h2 className="cxzcz font-montserrate xl:text-6xl lg:text-5xl md:text-4xl font-bold text-dark lg:mb-20 md:mb-10 text-center z-10 relative lg:before:content-[attr(before)] before:absolute before:bg-reachout xl:before:h-28 xl:before:w-30r md:before:h-28 before:h-28 before:w-64 sm:before:w-72 xl:before:w-30r md:before:w-72 before:bg-10% before:bg-no-repeat	md:before:-top-2 before:-left-0 before:right-0 before:mx-auto before:-z-10 text-4xl mb-8">
              <span className="text-yellow">Reach</span> Out
            </h2>
            <div className="py-7 xl:max-w-5xl xl:mx-auto drop-shadow-2xl bg-white lg:p-8 rounded-lg mt-4 md:py-9 relative z-10">
              {/* <div className='flex flex-wrap'>
                  <div className='lg:w-2/4 md:w-2/4 w-full 4 px-2.5 pb-6'>
                    <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                      <input type="text" placeholder="First Name*" className='border-0 bg-transparent outline-0 w-full' />
                    </fieldset>
                    <div className='text-red mt-1'>
                    </div>
                  </div>
                  <div className='lg:w-2/4 md:w-2/4 w-full px-2.5 pb-6'>
                    <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                      <input type="text" placeholder="Last Name*" className='border-0 bg-transparent outline-0 w-full' />
                    </fieldset>
                    <div className='text-red mt-1'>
                    </div>
                  </div>
                  <div className='lg:w-2/4 md:w-2/4 w-full px-2.5 pb-6'>
                    <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                      <input type="text" placeholder="Email*" className='border-0 bg-transparent outline-0 w-full' />
                    </fieldset> 
                    <div className='text-red mt-1'>
                    </div>
                  </div>
                  <div className='lg:w-2/4 md:w-2/4 w-full px-2.5 pb-6'>
                    <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                      <input type="text" placeholder="Subject" className='border-0 bg-transparent outline-0 w-full' />
                    </fieldset>
                    
                  </div>
                  <div className='w-full px-2.5 pb-6'>
                    <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                      <textarea placeholder="Leave us a message..." className='border-0 bg-transparent outline-0 w-full resize-none h-48'></textarea>
                    </fieldset>
                    
                  </div>
                  <div className='text-left w-full pl-2.5'>
                    <a href="#" className='font-montserrate text-base font-semibold	bg-black hover:bg-yellow hover:text-white hover:border-yellow text-white uppercase	inline-block py-3.5 px-12	rounded-md	'>Submit</a>
                  </div>
                </div> */}

              <Formik
                initialValues={{
                  firstname: "",
                  lastName: "",
                  email: "",
                }}
                validationSchema={validationSchema}
                onSubmit={(values, { resetForm }) => {
                  console.log(values);
                }}
              >
                {({ errors, touched }) => (
                  <>
                    <Form>
                      <div className="flex flex-wrap">
                        <div className="lg:w-2/4 md:w-2/4 w-full 4 px-2.5 pb-6">
                          <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                            {/* <input type="text" placeholder="First Name*" className='border-0 bg-transparent outline-0 width-full' /> */}
                            <Field
                              name="firstname"
                              placeholder="First Name*"
                              className="border-0 bg-transparent outline-0 w-full"
                            />
                          </fieldset>
                          <div className="text-red mt-1 text-xs">
                            <ErrorMessage name="firstname" />
                          </div>
                        </div>
                        <div className="lg:w-2/4 md:w-2/4 w-full px-2.5 pb-6">
                          <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                            {/* <input type="text" placeholder="Last Name*" className='border-0 bg-transparent outline-0 width-full' /> */}
                            <Field
                              name="lastName"
                              placeholder="Last Name*"
                              className="border-0 bg-transparent outline-0 w-full"
                            />
                          </fieldset>
                          <div className="text-red mt-1 text-xs">
                            <ErrorMessage name="lastName" />
                          </div>
                        </div>

                        <div className="lg:w-2/4 md:w-2/4 w-full px-2.5 pb-6">
                          <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                            {/* <input type="text" placeholder="Email*" className='border-0 bg-transparent outline-0 width-full' /> */}
                            <Field
                              name="email"
                              placeholder="Email*"
                              className="border-0 bg-transparent outline-0 w-full"
                            />
                          </fieldset>
                          <div className="text-red mt-1 text-xs">
                            <ErrorMessage name="email" />
                          </div>
                        </div>

                        <div className="lg:w-2/4 md:w-2/4 w-full px-2.5 pb-6">
                          <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                            
                            <Field
                              type="text"
                              name="subject"
                              placeholder="Subject*"
                              className="relative border-0 bg-transparent outline-0 w-full"
                            />
                          </fieldset>
                        </div>
                        <div className=" w-full px-2.5 pb-6">
                          <fieldset className='bg-white	rounded-md drop-shadow px-5	pt-2	pb-3'>
                            <textarea placeholder="Leave us a message..." className='border-0 bg-transparent outline-0 w-full resize-none h-48'></textarea>
                          </fieldset>
                        </div>
                        <div className="text-center w-full">
                          <button
                            type="submit"
                            className="font-montserrate text-base font-semibold	bg-black text-white uppercase	inline-block py-3.5 px-12	rounded-md">
                            Submit
                          </button>
                        </div>
                      </div>
                    </Form>
                  </>
                )}
              </Formik>
            </div>
            <div className="absolute lg:-bottom-20 left-0 right-0 md:bottom-10 -z-10 hidden md:block">
              <Image alt="Dots" src={dots3} className="mx-auto" />
            </div>
          </div>
          <div className="lg:flex md:hidden	absolute left-0 right-0 items-end	justify-between	mx-auto	xl:max-w-xxl bottom-0 lg:max-w-none -z-10 hidden">
            <div className="">
              <Image alt="leave1" src={leave1} />
            </div>
            <div className="">
              <Image alt="leave2" src={leave2} />
            </div>
          </div>

          <div className="absolute right-0 bottom-0 hidden md:block">
            <Image
              alt="Dots"
              src={dots}
              className="md:w-3/5 xl:w-full md:ml-auto md:w-10/12 xl:m-0"
            />
          </div>
        </section>
      </main>
    </>
  );
}
